#pragma once

#include "AxeTypes.h"

static const EffectLabel __EFFECT_NAME_TABLE[] PROGMEM = {
    {"COMP", "CMP"},
    {"GRAPHEQ", "GEQ"},
    {"PARAEQ", "PEQ"},
    {"AMP", "AMP"},
    {"CAB", "CAB"},
    {"REVERB", "REV"},
    {"DELAY", "DLY"},
    {"MULTITAP", "MTD"},
    {"CHORUS", "CHO"},
    {"FLANGER", "FLG"},
    {"ROTARY", "ROT"},
    {"PHASER", "PHR"},
    {"WAH", "WAH"},
    {"FORMANT", "FRM"},
    {"VOLUME", "VOL"},
    {"TREMOLO", "TRM"},
    {"PITCH", "PIT"},
    {"FILTER", "FIL"},
    {"DRIVE", "DRV"},
    {"ENHANCER", "ENH"},
    {"MIXER", "MIX"},
    {"SYNTH", "SYN"},
    {"VOCODER", "VOC"},
    {"MEGATAP", "MGT"},
    {"CROSSOVER", "XVR"},
    {"GATE", "GTE"},
    {"RINGMOD", "RNG"},
    {"MULTICOMP", "MBC"},
    {"TENTAP", "TTD"},
    {"RESONATOR", "RES"},
    {"LOOPER", "LPR"},
    {"TONEMATCH", "TMA"},
    {"RTA", "RTA"},
    {"PLEX", "PLX"},
    {"FBSEND", "SND"},
    {"FBRETURN", "RET"},
    {"MIDIBLOCK", "MIDI"},
    {"MULTIPLEXER", "MUX"},
    {"IRPLAYER", "IRP"},
    {"(UNKNOWN)", "???"},
};